name: Check and Publish

on:
  schedule:
    # ruffle's nightly building is at 0 0 * * *
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check new version and publish
        run: docker build -t ruffle_mirror . && docker run --rm --env NPM_TOKEN=${{ secrets.NPM_TOKEN }} ruffle_mirror